name: action-demo
on:
  push:
    branches: [ main ]
    paths-ignore: [.github/**]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:

jobs:
    Build:
      runs-on: ubuntu-latest
      name: Build
      steps:
      - uses: actions/checkout@v3.3.0
      - run: |
          echo: {{ github.event_name }}
          echo: {{ github.ref }}
          echo: {{ github.repository }}
            
      
